### ISSUE TITLE
Check base year for Arc runs

### ISSUE THREAD

**Issue by tomalrussell** [nismod/energy_demand#170]
Model run as configured in nismod `energy_demand_unconstrained` with Arc scenario data may be underestimating electricity and gas demand for 2015:
- Gas 180 TWh - National Grid reports 880 TWh total; or 545 TWh with exports and power generation excluded 
- Electricity 248 TWh - National Grid reports 334 TWh

In unconstrained mode, heat demand is output from the model as `heat` directly - the above calculations assume this is supplied by: 80% gas boilers with 80% efficiency and 20% heat pumps with 1.5 COP (coefficient of performance).

Possible sources of error or misconfiguration:
- model runs in constrained mode will output gas/electricity demands for heating end uses; these might give a different picture to the boiler/heat pump assumptions used above (though such a large difference is surprising)
- floor area inputs to the model have been recently configured; these might drive demand differently to the within-model virtual stock; test against previous configurations

**Comment by LahiruJayasuriya** [comment]
@tomalrussell I think trying to correct the `constrained` mode first would be feasible, as it outputs technology-specific gas/elec demands.
In the `unconstrained` mode we need to correct the total `heat` demand. This could be done by sector in energy demand model outputs, or, within the demand code itself where @eggimasv calculates fuel --> heat by 1 to 1 ratio.

**Comment by tomalrussell** [comment]
Linked to issue https://github.com/nismod/nismod2/issues/148 - closed by https://github.com/nismod/nismod2/pull/173
