### ISSUE TITLE
add methodology to project service sector floor area

### ISSUE THREAD

**Issue by eggimasv** [nismod/energy_demand#45]
Newscastle will provide most likely only base year floor area for the service sector. Future floor area of the service sector however needs to be projected (e.g. by establishing a link between GVA & floor area for the base year for the different industries across uk and then using future GVA to project grow in area)

**Comment by tomalrussell** [comment]
To be handled in [nismod/arc-floor-area](https://github.com/nismod/arc-floor-area), see https://github.com/nismod/arc-floor-area/issues/1
