### ISSUE TITLE
Setup and data

### ISSUE THREAD

**Issue by willu47** [nismod/energy_demand#80]
I think we can make it even easier to setup energy demand.

I have been running into issues with conflicts between the version of data and code I am using causing errors. One solution would be to link to a version of the energy demand data - this could be a zipped archive hosted on the ftp which is called energy_demand_data_v0.45.15

We could follow semantic versioning approaches - minor updates increment the rightmost digits, major updates increment the middle digits, non backwards-compatible changes to the data increment the leftmost digit.  

The codebase could then reference the minimum version of data required in a configuration file?

**Comment by RoaldL** [comment]
After repeatedly running into data-mismatch situations I have implemented the following for digital_comms: https://github.com/nismod/digital_comms/blob/master/setup.py

If you like, I can assist Sven in implementing this. Plus adding the semantic versioning and reference to minimum version.
